version: '3'

services:
  php:
    container_name: '${PREFIX_APP}php'
    image: rest_php:${TAG}
    build:
      context: ./docker/php
    volumes:
      - './:/var/www/html'

  server:
    container_name: '${PREFIX_APP}nginx'
    image: rest_nginx:${TAG}
    build:
      context: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - './:/var/www/html'

  db:
    container_name: '${PREFIX_APP}mysql'
    image: mysql:${TAG}
    build:
      context: ./docker/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      # - MYSQL_DATABASE=mysql
      # - MYSQL_USER=my_user
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'

networks:
  default:
    driver: bridge
    name: internet
